const unirest = require('unirest')
const fs = require('fs')

module.exports = function getEmoVu(file, res) {
  console.log(file)
  unirest.post('https://eyeris-emovu1.p.mashape.com/api/video/')
    .header('X-Mashape-Key', 'SKXDqHBIvymsh30AEv3FdBcR6xr2p1A09DGjsn6WN2zYHKhJlT')
    .field('ageGroupComputeInterval', 0)
    .field('computeAgeGroup', true)
    .field('computeEmotions', true)
    .field('computeEyeOpenness', false)
    .field('computeGender', true)
    .field('computeIdentity', false)
    .field('computeMetrics', true)
    .field('emotionsComputeInterval', 1000)
    .field('eyeOpennessComputeInterval', 0)
    .field('faceAnalysisType', 'AnalyzeLargestDetectedFace')
    .field('faceDetectionInterval', -1)
    .field('genderComputeInterval', 0)
    .field('identityComputeInterval', 0)
    .field('metricComputeInterval', 0)
    .field('minimumFaceDetectionConfidence', 3)
    .field('minimumFaceWidth', 20)
    .field('outputFrameRate', 0)
    .field('poseThreshold', 0.3491)
    .field('processingFrameRate', 1)
    .field('smoothingWindowTimeSpan', 250)
    .attach('videoFile', fs.createReadStream('public/uploads/' + file + '.mp4'))
    .field('viewedMediaDuration', 0)
    .end(function (response) {
      res.json(response.body, null, 2)
    })
}
